### ISSUE TITLE
Error generating proof

### ISSUE THREAD

**Issue by ptrwtts** [livepeer/merkle-mine#11]
I got the following error when trying to generate my proof. Node version v6.3.1

```
/Users/peter/Git/ptrwtts/merkle-mine/client/index.js:16
const main = async () => {
                   ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

Command I ran:

`node client/index.js --recipient 0x......123`

**Comment by ptrwtts** [comment]
Dug deeper and as suspected, old node version is to blame. async functions are not supported before node version 7.6

**Comment by yondonfu** [comment]
Yep these scripts had only been tested with Node.js v8.5.0. Will make a note to highlight that requirement more prominently.
