### ISSUE TITLE
Error generating proof

### ISSUE THREAD

**Issue by trummax** [livepeer/merkle-mine#12]
I got the following error when trying to generate my proof. Node version v8.11.1

Using MerkleMine contract 0x8e306b005773bee6ba6a6e8972bc79d766cc15c8
Creating Merkle tree...
Created Merkle tree with root 0x53f35a304a1e1e20d6648e09bb3073ccd44a5bf1638a01355897a71e801879f8 and 2598071 leaves
Some checks failed!
Try using the accounts file at https://gateway.ipfs.io/ipfs/QmQbvkaw5j8TFeeR7c5Cs2naDciUVq9cLWnV3iNEzE784r
Please visit livepeer.org to learn how to start participating in the Livepeer network
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/johnsmith/Downloads/merkle-mine/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/johnsmith/Downloads/merkle-mine/node_modules/web3-providers-http/src/index.js:73:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/johnsmith/Downloads/merkle-mine/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/johnsmith/Downloads/merkle-mine/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/Users/johnsmith/Downloads/merkle-mine/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/Users/johnsmith/Downloads/merkle-mine/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by yondonfu** [comment]
Hey @trummax what command (including flags) are you running?

**Comment by trummax** [comment]
@yondonfu 
node client/index.js --recipient 0x4...3bd01
