### ISSUE TITLE
error when generating token allocation

### ISSUE THREAD

**Issue by oneyesoneno** [livepeer/merkle-mine#13]
Hi hadi here (aka. 0x88).. i am experimenting with generating token allocation.. i am running this command 

node client/index.js --generate --recipient 0x7755B69903BcbCc419260dBb65772412E0C4ad2b --caller 0x88e103b26e1a4ce226739d37d356b22afbfeed85 --datadir /root/.lpData/ --gasprice 10000000000 -gasLimit 2000000

i wonder why i got this error:

> Unlocked caller account 0x88e103b26e1a4ce226739d37d356b22afbfeed85
> Error: Returned error: gas required exceeds allowance or always failing transaction
>     at Object.ErrorResponse (/root/merkle-mine/node_modules/web3-core-helpers/src/errors.js:29:16)
>     at /root/merkle-mine/node_modules/web3-core-requestmanager/src/index.js:140:36
>     at XMLHttpRequest.request.onreadystatechange (/root/merkle-mine/node_modules/web3-providers-http/src/index.js:77:13)
>     at XMLHttpRequestEventTarget.dispatchEvent (/root/merkle-mine/node_modules/xhr2/lib/xhr2.js:64:18)
>     at XMLHttpRequest._setReadyState (/root/merkle-mine/node_modules/xhr2/lib/xhr2.js:354:12)
>     at XMLHttpRequest._onHttpResponseEnd (/root/merkle-mine/node_modules/xhr2/lib/xhr2.js:509:12)
>     at IncomingMessage.<anonymous> (/root/merkle-mine/node_modules/xhr2/lib/xhr2.js:469:24)
>     at emitNone (events.js:111:20)
>     at IncomingMessage.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> 
 I am very sure, i have more than enough eth to pay for the gas... thanks you.

**Comment by yondonfu** [comment]
Hi @oneyesoneno it looks like you specified a recipient address that is different from your specified caller address. At the moment, in order to generate a token allocation for a recipient address you must submit the relevant transaction from the recipient address - you cannot generate a token allocation for a recipient address by submitting a transaction from a third party caller address. This would explain the part of the error message saying "always failing transaction".

However, starting from the `callerAllocationStartBlock` which is equal to 6034099, you will be able to generate a token allocation for a recipient address by submitting a transaction from a third party caller address.

**Comment by oneyesoneno** [comment]
Thank you for the reply.....
